### PR TITLE
Add db management system libraries for rest of the databases

### PR DESCRIPTION
**Pull request by cyanogus**
This was added for the currency system's database. Since no problems were reported from use after it's implementation, I feel like it's time to implement this change to the other databases as well.

### CODE REVIEW

**Comment by cyanogus** [comment]
So far I've worked on the levelling db part of it. I'm currently working on the items db part and the other ones are yet to be completed.

**Comment by cyanogus** [comment]
Added database library support for weather cog.

**Comment by cyanogus** [comment]
Alternative pull request was made for Weather DB commands. #310 
Another alternative pull request was also made for Levelling DB commands. #307

**Comment by notsniped** [comment]
This PR contains the following topics which need to be replicated in other PRs:

- [ ] Items
- [ ] Levels
- [ ] Weather

**Comment by notsniped** [comment]
Am currently working on items db support.

**Comment by notsniped** [comment]
A new pull request for base implementation of items db has been made.
#312

**Comment by notsniped** [comment]
Now, for the items db, full migration of commands using __items__, and testing will be done.

**Comment by notsniped** [comment]
A complete version of items db was made at #313

**Comment by notsniped** [comment]
The PRs mentioned above have covered all of the changes of this one PR. This PR will now be closed. Thank you for your time!

**Comment by notsniped** [comment]
PRs: #307 #310 #312 #313

**Pull request closed without merging**
